-- MySQL Script generated by MySQL Workbench
-- Wed Sep  9 14:37:45 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `cpf_pk` INT NULL,
  `nome` CHAR(125) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`cpf_pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ANIMAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ANIMAL` (
  `codigo_pk` INT NULL,
  `cpf_pk` INT NULL,
  `nome` CHAR(125) NOT NULL,
  `data_nacimento` CHAR(8) NOT NULL,
  `raça` CHAR(30) NOT NULL,
  `CLIENTE_cpf_pk` INT NOT NULL,
  PRIMARY KEY (`codigo_pk`, `cpf_pk`),
  INDEX `fk_ANIMAL_CLIENTE1_idx` (`CLIENTE_cpf_pk` ASC) VISIBLE,
  CONSTRAINT `fk_ANIMAL_CLIENTE1`
    FOREIGN KEY (`CLIENTE_cpf_pk`)
    REFERENCES `mydb`.`CLIENTE` (`cpf_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VETERINARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VETERINARIO` (
  `crm_pk` INT NULL,
  `nome` CHAR(125) NOT NULL,
  `data_admição` CHAR(8) NOT NULL,
  `salario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`crm_pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ANIMAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ANIMAL` (
  `codigo_pk` INT NULL,
  `cpf_pk` INT NULL,
  `nome` CHAR(125) NOT NULL,
  `data_nacimento` CHAR(8) NOT NULL,
  `raça` CHAR(30) NOT NULL,
  `CLIENTE_cpf_pk` INT NOT NULL,
  PRIMARY KEY (`codigo_pk`, `cpf_pk`),
  INDEX `fk_ANIMAL_CLIENTE1_idx` (`CLIENTE_cpf_pk` ASC) VISIBLE,
  CONSTRAINT `fk_ANIMAL_CLIENTE1`
    FOREIGN KEY (`CLIENTE_cpf_pk`)
    REFERENCES `mydb`.`CLIENTE` (`cpf_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CONSULTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CONSULTA` (
  `crm_pk` INT NULL,
  `codigo_pk` INT NULL,
  `data` CHAR(8) NOT NULL,
  `hora` CHAR(4) NOT NULL,
  `motivo` VARCHAR(125) NOT NULL,
  `VETERINARIO_crm_pk` INT NOT NULL,
  `ANIMAL_codigo_pk` INT NOT NULL,
  `ANIMAL_cpf_pk` INT NOT NULL,
  PRIMARY KEY (`crm_pk`, `codigo_pk`),
  INDEX `fk_CONSULTA_VETERINARIO1_idx` (`VETERINARIO_crm_pk` ASC) VISIBLE,
  INDEX `fk_CONSULTA_ANIMAL1_idx` (`ANIMAL_codigo_pk` ASC, `ANIMAL_cpf_pk` ASC) VISIBLE,
  CONSTRAINT `fk_CONSULTA_VETERINARIO1`
    FOREIGN KEY (`VETERINARIO_crm_pk`)
    REFERENCES `mydb`.`VETERINARIO` (`crm_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONSULTA_ANIMAL1`
    FOREIGN KEY (`ANIMAL_codigo_pk` , `ANIMAL_cpf_pk`)
    REFERENCES `mydb`.`ANIMAL` (`codigo_pk` , `cpf_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
